//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Email { get; set; }
        public string Project { get; set; }
        public string City { get; set; }
        public string Street { get; set; }
        public string House_number { get; set; }
        public string Apartment_number { get; set; }
        public string username { get; set; }
        public string Zip_code { get; set; }
    }
}
